### ISSUE TITLE
Incorrectly capitalised words

### ISSUE THREAD

**Issue by devinpearson** [OfferZen-Community/developers-finance#36]
https://www.developersfinance.guide/docs/tax/income-tax-and-capital-gains-tax

income tax and capital gains shouldn't be capitalised if im not mistaken.

Capital gains does enter the income tax calculation, in that a specific percentage of Capital gains are included in your taxable income when calculating Income tax.

**Comment by shannagh11** [comment]
Fixed - thanks @devinpearson :)
