### ISSUE TITLE
Spelling mistake in Fund Raising

### ISSUE THREAD

**Issue by devinpearson** [OfferZen-Community/developers-finance#37]
https://www.developersfinance.guide/docs/building-a-business/fundraising

Back Foot instead of Back Foort

If you are Back Foort Fundraising, the messaging is negative

**Comment by devinpearson** [comment]
another further down the page

Back Foot messgaing should be messaging

**Comment by devinpearson** [comment]
missing space between these two sentences.

Runway is the amount of time you have left until you run out of cash and need to shut down the company.When you run out of runway you will need to fundraise or you will die.

**Comment by shannagh11** [comment]
All spelling errors have been fixed - thanks @devinpearson!
